# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build executable
      id: pyinstaller
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.10'
        spec: 'StudentOnDuty.py'
        requirements: 'requirements.txt'
        options: --onefile, --name "SOD_install",
        
    - name: Delete release
      uses: cb80/delrel@latest
      with:
        tag: 'newest-push'
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: '${{ steps.pyinstaller.outputs.executable_path}}/SOD_install'
        body: |
          Newest Push
        draft: false
        prerelease: true
        tag: newest-push
        allowUpdates: true

